config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify_email, reset_password

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('verify/<str:token>/', verify_email, name='verify'),
    path('reset_password/', reset_password, name='reset_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):

    username = None
    email = models.EmailField(max_length=100, unique=True, verbose_name='почта')
    avatar = models.ImageField(upload_to='users/avatars', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=20, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=20, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=100, **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import string

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        token = ''.join(random.sample(string.digits + string.ascii_letters, 12))
        self.object.token = token
        self.object.is_active = False
        self.object.save()
        url = 'http://127.0.0.1:8000/users/verify/' + token

        if form.is_valid():
            send_mail(
                subject='Подтверждение регистрации',
                message=f"""Для подтверждения регистрации и присоединении к команде перейдите по ссылке: {url}
                        Внимание! Если вы не понимаете, почему Вам пришло это письмо, просто проигнорируйте его""",
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email]
            )
        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def verify_email(request, token):
    user = User.objects.filter(token=token).first()
    if user is not None:
        user.is_active = True
        user.save()
        return redirect('users:login')


def reset_password(request):
    if request.method == 'POST':
        input_email = request.POST.get('email')
        user = User.objects.filter(email=input_email).first()
        password = User.objects.make_random_password()
        user.set_password(password)
        user.save(update_fields=['password'])
        send_mail(
            subject='Сброс пароля',
            message=f'''Вы успешно сбросили пароль для аккаунта {input_email}.\n Ваш новый пароль: {password}''',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[input_email]
        )

    return render(request, 'users/reset_password.html')

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                      Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        Войти
                    </button>
                    <a href="{% url 'users:reset_password' %}" class="btn btn-link">Восстановить пароль</a>
                </div>
            </div>
        </div>
</form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                      Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        Регистрация
                    </button>
                </div>
            </div>
        </div>

</form>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'catalog/base.html' %}

{% block content %}
        <div class="col-12">
            <form method="post" enctype="multipart/form-data" class="row mt-5">
                <div class="col-4"></div>
                <div class="col-4 ml-5">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Сброс пароля
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <input type="text" name="email" class="form-control mb-2" id="email"
                                   placeholder="Введите email"
                                   required>
                            <button class="btn btn-danger" type="submit">
                                Подтвердить
                            </button>
                            <a href="{% url 'users:login' %}" class="btn btn-warning">Отмена</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                      Профиль
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        Сохранить
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
{% endblock %}

users/templates/users/verify_email.html
{% extends 'catalog/base.html' %}

{% block content %}
    <main role="main">
        <div class="col-12">
            <form method="post" enctype="multipart/form-data" class="row mt-5">
                <div class="col-4"></div>
                <div class="col-4 ml-5">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Подтвердите электронную почту
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success" type="submit">
                                Подтвердить
                            </button>
                            <a href="{% url 'users:login' %}" class="btn btn-danger">Отмена</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <hr>
    </main>
{% endblock %}