catalog/urls.py
from django.urls import path
from catalog.views import CatalogListView, ArticleCreateView, ArticleListView, ArticleUpdateView, ArticleDetailView, \
    ArticleDeleteView, BaseListView, CategoryListView, CategoryCreateView, CategoryDeleteView, sort_articles


urlpatterns = [
    path('', ArticleListView.as_view(), name='/'),
    path('base/', BaseListView.as_view()),
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete'),
    path('categories/', CategoryListView.as_view(), name='category'),
    path('create_categories/', CategoryCreateView.as_view(), name='create_category'),
    path('delete_categories/<int:pk>/', CategoryDeleteView.as_view(), name='delete_category'),
    path('sort/<int:pk>', sort_articles, name='sort_category')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify_email, reset_password

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('verify/<str:token>/', verify_email, name='verify'),
    path('reset_password/', reset_password, name='reset_password'),
]

catalog/models.py
from django.db import models
from django.contrib.auth import get_user_model

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    category_name = models.CharField(max_length=150, verbose_name='Категория')

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Описание')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.title} ({self.slug})'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

catalog/forms.py
class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.shortcuts import render
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from catalog.models import Article, Category


class CategoryListView(ListView):
    model = Category
    template_name = "catalog/categories_list.html"


class CategoryCreateView(CreateView):
    model = Category
    fields = ('category_name',)
    success_url = reverse_lazy('category')

    def form_valid(self, form):
        if form.is_valid():
            new_content = form.save()
            new_content.save()

        return super().form_valid(form)


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('category')


class BaseListView(ListView):
    model = Article
    template_name = "catalog/base.html"


class CatalogListView(ListView):
    model = Article
    template_name = "catalog/article_list.html"


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'content', 'category',)
    success_url = reverse_lazy('catalog')

    def form_valid(self, form):
        if form.is_valid():
            new_content = form.save()
            new_content.slug = slugify(new_content.title)
            new_content.save()

        return super().form_valid(form)


class ArticleListView(ListView):
    model = Article

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        return queryset


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'content', 'category',)

    def form_valid(self, form):
        if form.is_valid():
            new_content = form.save()
            new_content.slug = slugify(new_content.title)
            new_content.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('view', args=[self.kwargs.get('pk')])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('catalog')


def sort_articles(request, **kwargs):
    category_pk = kwargs.get('pk')
    queryset = Article.objects.filter(category=category_pk)
    context = {'queryset': queryset, 'category_pk': category_pk}
    return render(request, 'catalog/category_sort.html', context)

catalog/templates/catalog/article_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<main role="main">

    <h1 class="display text-center mt-4">{{ object.title }}</h1>

    <div class="col-12 d-flex justify-content-center align-items-center">
        <div class="card d-flex justify-content-center">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить "{{ object.title }}"?</p>
                    <button class="btn btn-danger" type="submit">Подтвердить</button>
                    <a href="{% url 'catalog' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

catalog/templates/catalog/article_detail.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}

<div class="container">
    <a class="btn btn-outline-success" href="{% url 'update' object.pk %}">Редактировать запись</a>
    <a class="btn btn-outline-danger" href="{% url 'delete' object.pk %}">Удалить запись</a>
    <h1 class="display-4">{{ object.title }} ({{ object.slug }})</h1>
    <h6 class="display-9">Категория: {{ object.category }}</h6>
    <p>Запить создана {{ object.created_at }}</p>
    <p>Количество просмотров: {{ object.views_count }}</p>
</div>
<div class="container">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <p>
                    {{ object.content }}
                </p>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/article_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<main role="main">
    <div class="col-12">
        <div class="container">
            <h2 class="display-4">Заполните поля формы</h2>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary w-100" type="submit">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/article_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<main role="main">
    <div class="col-12">
        <div class="container px-5 py-5 pt-md-5 pb-md-5 mx-auto text-center">
            {% if user.is_authenticated %}
                 <a href="{% url 'create' %}" class="btn btn-sm btn-outline-primary " >Написать статью</a>
            {% endif %}
        </div>
    </div>
    <div class="container mb-5">
        <div class="row">
            {% for object in object_list %}
            <div class="card mb-4 mr-5" style="width: 20rem;">
                <img src="{{ object.preview|mediapath }}" width="600" height="520" alt="Изображение отсутствует">
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">{{ object.content|truncatechars:100 }} </p>
                    <a href="{% url 'view' object.pk %}" class="btn btn-sm btn-outline-primary" role="button">Посмотреть</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'update' object.pk %}" class="btn btn-sm btn-outline-primary">Изменить</a>
                        <a href="{% url 'delete' object.pk %}" class="btn btn-sm btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                    <a class="btn btn-warning" href="{% url 'toggle_activity' object.pk %}">Снять публикацию</a>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">BestArticle</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/catalog/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'category' %}">Категории</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>
<div class="pricing-header px-3 py-3 pt-md-3 pb-md-2 mx-auto text-center">
    <p class="lead">BestArticle - один из лучших сайтов, где вы можете почитать статьи, написанные пользователями, а также разместить свою статью!</p>
</div>
<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-3 my-md-5 pt-md-2 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <a href="#">В начало</a>
                <p class="float-end mb-1"></p>
                <p class="mb-1">BestArticle&copy; 2023</p>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/categories_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<main role="main">
    <div class="container mb-5">
        <div class="row">
            <div class="col-12 col-md mb-2">
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-success" href="{% url 'create_category' %}">Добавить категорию</a>
                {% endif %}
                {% for object in object_list %}
                    <div class="card-body">
                        <a class="btn btn-outline-primary" href="{% url 'sort_category' object.pk %}">{{ object.category_name }}</a>
                        {% if user.is_authenticated %}
                            <a class="btn btn-outline-danger" href="{% url 'delete_category' object.pk %}">Удалить категорию</a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/category_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<main role="main">
    <h1 class="display text-center mt-4">{{ object.title }}</h1>
    <div class="col-12 d-flex justify-content-center align-items-center">
        <div class="card d-flex justify-content-center">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить "{{ object.category_name }}"?</p>
                    <button class="btn btn-danger" type="submit">Подтвердить</button>
                    <a href="{% url 'catalog' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/category_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<main role="main">
    <div class="col-12">
        <div class="container">
            <h2 class="display-4">Заполните наименование</h2>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary w-100" type="submit">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/category_sort.html
{% extends 'catalog/base.html' %}

{% block content %}
<main role="main">
    <div class="col-12 mb-2">
        {% if user.is_authenticated %}
            <a class="btn btn-primary form-control" href="{% url 'create' %}">Написать статью</a>
        {% else %}
            <a class="btn btn-primary form-control" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button"
           aria-expanded="false" aria-controls="multiCollapseExample1">Написать статью</a>
            <div class="col-6">
                <div class="collapse multi-collapse mb-5" id="multiCollapseExample1">
                    <div class="card card-body mb-5">
                        Войдите в свой аккаунт или зарегистрируйтесь, чтобы написать статью!
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    <div class="container mb-2">
        <div class="row">
            <div class="col-12 col-md">
                <div class="card-body">
                    <a class="btn btn-outline-primary" href="{% url 'category' %}">Категории</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mb-5">
        <div class="row">
            {% for object in queryset %}
            <div class="card mb-3 mr-5" style="width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">{{ object.title }}</h4>
                    <p class="card-text">{{ object.content|truncatechars:100 }}</p>
                    <p class="card-text">Категория: {{ object.category }}</p>
                    <a href="{% url 'view' object.pk %}" class="btn btn-sm btn-outline-primary" role="button">Посмотреть</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'update' object.pk %}" class="btn btn-sm btn-outline-primary">Изменить</a>
                    <a href="{% url 'delete' object.pk %}" class="btn btn-sm btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}